import { Geist, Geist_Mono } from 'next/font/google';
// import 'bootstrap/dist/css/bootstrap.min.css';

import '@/styles/globals.css';
import Navbar from '@/components/navbar/Navbar'; // Import your Navbar

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Umer Gull',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar /> {/* Navbar visible on all pages */}
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
